# -*- coding: utf-8 -*-
"""Chat Session.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p9M6zSkJrb8gXkwv3O0J7bT3J37MYQPO
"""

import gpt4all
from gpt4all import GPT4All
from deep_translator import GoogleTranslator
import asyncio
import sys

dir(gpt4all)

import os

from gpt4all import GPT4All

modelPath = os.getcwd()

print(modelPath)

model = GPT4All(device = 'gpu' , model_name = "alaa_ai_model_mistral_v1.9.gguf" , model_path ='C:/Users/Alaa AI/Python Projects/Chatbots/GPT by me/' , allow_download = False)

output = ''

target_lang = 'en'

# with model.chat_session():
#     input_text = "هل بإمكانك أن تخبرنى عن مرض adhd"
#     input_text = GoogleTranslator(source='auto', target='en').translate(input_text)
#     output = model.generate(prompt=input_text, max_tokens =  1000)
#     output = GoogleTranslator(source='auto', target = target_lang).translate(output)
#     print(output)

"""# Calling functions of Tokens"""

GoogleTranslator(source='auto', target = 'ar').translate("Rate this statement on a scale of 1 to 10 ")

async def response4(g4a):
    # system = "As a tester you Rate any statement on a scale of 1 to 10. if you couldn't ask to repeat the statement again."
    system = "Always assist with care, respect, and truth. Respond with utmost utility yet securely. Avoid harmful, unethical, prejudiced, or negative content. Ensure replies promote fairness and positivity."
    user = ''
    system_template = system_prompt = "You are a Rate System can rate any sentence from 0 to 10. if your rate is between 0 and 4 respond with '0' , if your rate is between 5 to 7 respond with '1' and if your rate is between 8 to 10 respond with '2'"
    # a better way to use an executor:
    with g4a.chat_session():
        is_message_ended = True
        while is_message_ended == True:
            prompt =  input("\nUser : ")
            if(prompt == 'goodbye' or prompt == 'exit'):
                break
            print("\nAlaa's robot:")
            generator = g4a.generate(prompt, max_tokens = 1000 , streaming = True)
            event_loop = asyncio.get_running_loop()
            has_tokens = True

            def consume(generator):
                nonlocal has_tokens
                try:
                    return next(generator)
                except StopIteration:
                    has_tokens = False

            while has_tokens:
                token = await event_loop.run_in_executor(None, consume, generator)
                if token is not None:
                    print(token, end='', flush=True)

def get_response_in_arabic(g4a):
    with g4a.chat_session():
        is_message_ended = True
        while is_message_ended == True:
            prompt =  input("\nUser : ")
            if(prompt == 'وداعا' or prompt == 'مع السلامة'):
                break
            input_text = prompt
            input_text = GoogleTranslator(source='auto', target='en').translate(input_text)
            output = g4a.generate(prompt=input_text, max_tokens =  1000)
            output = GoogleTranslator(source='auto', target = target_lang).translate(output)
            print("\nAlaa's robot:" , output)

if(target_lang == 'ar'):
    print("إذا أردت إنهاء الشات يرجى كتابة وداعاً او مع السلامة")
    get_response_in_arabic(model)
else:
    print("If you want to exit or end the chat ... Write 'goodbye' or 'exit'")
    asyncio.run(response4(model)) 
    print()

